version: '3'

services:
  apache:
    # Install: docker-php-ext-install pdo pdo_mysql mysqli
    # enable mod_rewrite: a2enmod rewrite
    image: php:8.0-apache
    volumes:
      - './:/var/www/html/' # DO NOT use this mapping in production environments! NEVER! NO!
    ports:
      - 8080:80
    links:
      - mariadb:db

  mariadb:
    image: mariadb:10.5
    ports:
      - 3306:3306
    env_file:
      - .env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mariadb:db
    depends_on:
      - mariadb
    ports:
      - 8081:80
    environment:
      PMA_ARBITRARY: 0
